In [3]:
import pandas as pd
import os

In [13]:
data = []

for f in os.listdir("C://Data//PseudoPFLOW//activity_v2//12"):
    df = pd.read_csv("C://Data//PseudoPFLOW//activity_v2//12//"+f, names=['pid', 'age','gender','occupation','starttime','duration', 'purpose', 'lon', 'lat', 'address'])
    data.append(df)

chiba_act = pd.concat(data, axis=0)
chiba_act

【139.92300735680504， 139.96621967375887】 lat【35.88552717539729, 35.9117804553585】,的部分

,pid,age,gender,occupation,starttime,duration,purpose,lon,lat,address
0,27820302,49,1,21,0,24300,1,140.146250,35.580170,12101
1,27820302,49,1,21,24300,21600,2,140.141157,35.575586,12101
2,27820302,49,1,21,45900,18900,500,140.148145,35.589510,12101
3,27820302,49,1,21,64800,21600,1,140.146250,35.580170,12101
4,27820303,83,2,21,0,27900,1,140.146171,35.579800,12101
...,...,...,...,...,...,...,...,...,...,...
19769,33922887,18,2,15,23400,33300,3,140.091904,35.082068,12223
19770,33922887,18,2,15,56700,29700,1,139.877559,35.148783,12463
19771,33922888,6,1,12,0,27000,1,139.877559,35.148783,12463
19772,33922888,6,1,12,27000,26100,3,139.837717,35.110789,12463
19773,33922888,6,1,12,53100,33300,1,139.877559,35.148783,12463

In [23]:
kashiwa_act = chiba_act[(chiba_act['lon']<139.96621967375887)&(chiba_act['lon']>139.92300735680504)&(chiba_act['lat']<35.9117804553585)&(chiba_act['lat']>35.88552717539729)]
len(kashiwa_act['pid'].unique())

55154

In [25]:
kashiwa_act_final = chiba_act[chiba_act['pid'].isin(kashiwa_act['pid'].unique().tolist())]
kashiwa_act_final

,pid,age,gender,occupation,starttime,duration,purpose,lon,lat,address
14764,27830608,38,1,21,0,29700,1,140.139817,35.615729,12101
14765,27830608,38,1,21,29700,36000,2,139.930377,35.903679,12217
14766,27830608,38,1,21,65700,20700,1,140.139817,35.615729,12101
19583,27833957,40,1,21,0,24300,1,140.132412,35.577816,12101
19584,27833957,40,1,21,24300,39600,2,139.951632,35.910448,12217
...,...,...,...,...,...,...,...,...,...,...
7899,33823141,34,1,21,31500,32400,500,140.515988,35.737673,12235
7900,33823141,34,1,21,63900,22500,1,140.477631,35.697478,12410
4387,33902612,48,2,21,0,24300,1,140.187957,35.253665,12441
4388,33902612,48,2,21,24300,41400,2,139.951091,35.893670,12217
4389,33902612,48,2,21,65700,20700,1,140.187957,35.253665,12441

In [27]:
kashiwa_act_final.to_csv('kashiwa_act_final.csv', index=False, header=False)

In [15]:
data = []

for f in os.listdir("C://Data//PseudoPFLOW//activity_v2//13"):
    df = pd.read_csv("C://Data//PseudoPFLOW//activity_v2//13//"+f, names=['pid', 'age','gender','occupation','starttime','duration', 'purpose', 'lon', 'lat', 'address'])
    data.append(df)

tokyo_act = pd.concat(data, axis=0)
tokyo_act

,pid,age,gender,occupation,starttime,duration,purpose,lon,lat,address
0,33922893,59,2,21,0,21600,1,139.741445,35.683175,13101
1,33922893,59,2,21,21600,40500,2,140.302775,35.754200,12233
2,33922893,59,2,21,62100,24300,1,139.741445,35.683175,13101
3,33922894,33,2,21,0,27000,1,139.738391,35.682707,13101
4,33922894,33,2,21,27000,31500,2,139.742062,35.626164,13103
...,...,...,...,...,...,...,...,...,...,...
3332,47225661,4,2,11,58500,27900,1,142.204310,27.066090,13421
3333,47225712,5,2,11,0,27000,1,142.203810,27.071780,13421
3334,47225712,5,2,11,27000,27900,3,142.160386,26.641405,13421
3335,47225712,5,2,11,54900,31500,1,142.203810,27.071780,13421
3336,47225735,21,1,15,0,86400,1,142.203810,27.071780,13421

In [29]:
kashiwa2_act = tokyo_act[(tokyo_act['lon']<139.96621967375887)&(tokyo_act['lon']>139.92300735680504)&(tokyo_act['lat']<35.9117804553585)&(tokyo_act['lat']>35.88552717539729)]
len(kashiwa2_act['pid'].unique())

893

In [33]:
kashiwa_act_final2 = tokyo_act[tokyo_act['pid'].isin(kashiwa2_act['pid'].unique().tolist())]
kashiwa_act_final2

,pid,age,gender,occupation,starttime,duration,purpose,lon,lat,address
7384,33927474,34,1,21,0,24300,1,139.779830,35.698559,13101
7385,33927474,34,1,21,24300,37800,2,139.952379,35.909688,12217
7386,33927474,34,1,21,62100,24300,1,139.779830,35.698559,13101
38312,33946793,34,2,21,0,22500,1,139.777262,35.697865,13101
38313,33946793,34,2,21,22500,52200,2,139.953482,35.894379,12217
...,...,...,...,...,...,...,...,...,...,...
123816,47043742,66,1,21,60300,26100,1,139.533285,35.713700,13229
159452,47070244,45,1,21,0,26100,1,139.563160,35.739521,13229
159453,47070244,45,1,21,26100,5400,2,139.948506,35.909905,12217
159454,47070244,45,1,21,31500,27900,500,139.950001,35.907631,12217
159455,47070244,45,1,21,59400,27000,1,139.563160,35.739521,13229

In [35]:
kashiwa_act_final2.to_csv('kashiwa_act_final2.csv', index=False, header=False)