In [6]:
import pandas as pd
import os

In [32]:
data = []
i = 0
for f in os.listdir(r"D:\large\PseudoPFLOW\trip\13"):

    df = pd.read_csv(r"D:\large\PseudoPFLOW\trip\13"+ "\\" + f, names=["pid", "time", "slon", "slat", "elon", "elat", "mode", "purpose", "occupation"])
    data.append(df)
    i +=1 
    if i ==10:
        break
trips = pd.concat(data, axis=0)
trips

,pid,time,slon,slat,elon,elat,mode,purpose,occupation
0,33922893,16485,139.741445,35.683175,140.302775,35.754200,3,2,21
1,33922893,56975,140.302775,35.754200,139.741445,35.683175,3,1,21
2,33922894,25620,139.738219,35.682536,139.737214,35.685208,1,2,21
3,33922894,27120,139.737214,35.685208,139.738742,35.628514,4,2,21
4,33922894,57300,139.742783,35.625243,139.738742,35.628514,1,400,21
...,...,...,...,...,...,...,...,...,...
648941,36506763,23400,139.666702,35.624050,139.676464,35.617819,1,3,11
648942,36506763,23460,139.676464,35.617819,139.685297,35.628847,4,3,11
648943,36506763,52140,139.689962,35.627267,139.685297,35.628847,1,1,11
648944,36506763,52260,139.685297,35.628847,139.676464,35.617819,4,1,11
648945,36506764,24887,139.666663,35.623948,139.699165,35.626527,3,3,11

In [34]:
trips["mode"].value_counts()

mode
1    1890888
4    1688990
3    1562929
0     773353
2     319589
5        453
Name: count, dtype: int64

In [44]:
len(trips["pid"].unique())

8508331

In [22]:
trips[trips["mode"]==5]

,pid,time,slon,slat,elon,elat,mode,purpose,occupation
14,27820305,38700,140.020942,35.691572,140.069919,35.726342,5,2,21
16,27820305,61440,140.069919,35.726342,140.028775,35.700600,5,1,21
22,27820306,40980,140.090561,35.700764,140.095014,35.681172,5,2,21
24,27820306,71400,140.095014,35.681172,140.090561,35.700764,5,1,21
28,27820308,21900,140.147894,35.582653,140.133436,35.581247,5,2,21
...,...,...,...,...,...,...,...,...,...
759223,28020605,68940,140.114475,35.612456,140.127403,35.619189,5,1,14
759230,28020635,27300,140.127403,35.619189,140.114475,35.612456,5,3,11
759232,28020635,30300,140.111828,35.612969,140.114636,35.609528,5,3,11
759234,28020635,61500,140.114636,35.609528,140.111828,35.612969,5,1,11
759236,28020635,64740,140.114475,35.612456,140.127403,35.619189,5,1,11