In [3]:
import pandas as pd

In [5]:
od = pd.read_csv("C:\Data\PseudoPFLOW\processing\city_census_od.csv")
od

        city1  city2  isCommuter  isMale  isHome  volume
0        1101   1101        True    True    True    3085
1        1101   1101        True   False    True    2920
2        1101   1101        True    True   False   28925
3        1101   1101       False    True   False    2399
4        1101   1101        True   False   False   29061
...       ...    ...         ...     ...     ...     ...
585013  47382  47207       False    True   False       1
585014  47382  47208        True    True   False       1
585015  47382  47208       False   False   False       1
585016  47382  28107       False   False   False       1
585017  47382  28206       False   False   False       1

[585018 rows x 6 columns]

In [11]:
od[(od['city1']==22131)&(od['city2']==22131)]

        city1  city2  isCommuter  isMale  isHome  volume
316991  22131  22131        True    True    True    5830
316992  22131  22131        True   False    True    4661
316993  22131  22131        True    True   False   31188
316994  22131  22131       False    True   False    4301
316995  22131  22131        True   False   False   30104
316996  22131  22131       False   False   False    3256

In [17]:
volume_sum = od.groupby(['city1', 'city2'])['volume'].sum().reset_index()
# volume_sum = volume_sum.sort_values(by='volume', ascending=False)

volume_sum

        city1  city2  volume
0        1101   1101   69157
1        1101   1102    5990
2        1101   1103    3462
3        1101   1104    3177
4        1101   1105    3564
...       ...    ...     ...
321219  47382  28107       1
321220  47382  28206       1
321221  47382  47207       1
321222  47382  47208       2
321223  47382  47382    1316

[321224 rows x 3 columns]